serverName: "GoatCore Server"
sendFirstJoinMessage: true
firstJoinMessage: "&e&l%player%&r&a, welcome to &b%servername%&a!"
sendJoinMessage: true
joinMessage: "&e&l%player% &r&ahas joined &b%servername%&a!"
sendQuitMessage: true
quitMessage: "&e&l%player% &r&ahas left &b%servername%&a!"
lobby:
  teleportOnJoin: true